services:
  korus-auth:
    image: korus-auth
    build: ../auth
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      JWT_REFRESH_TOKEN_EXPIRE_DAYS: ${JWT_REFRESH_TOKEN_EXPIRE_DAYS}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}

